import {ROOMS,REFEREE,UNKNOWN,endpoint,decodeRoom,groups,decimal,feedStatus,compatible,observations,search,verifyEnvelope} from './core.js';
const $=id=>document.getElementById(id), feeds={}, history=Object.fromEntries(ROOMS.map(t=>[t,[]]));
let lastAttempt=0,busy=false,index=new Map(),lastSuccess=null;
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(cls)n.className=cls;return n;};
const fmt=x=>x===undefined||x===null?'Not published':typeof x==='number'?x.toLocaleString('en-US'):String(x);
const stamp=x=>Number.isFinite(Date.parse(x))?new Date(x).toISOString().replace('T',' ').replace(/\.\d+Z$/,' UTC'):'Not published';
function copyButton(did){const b=el('button','Copy','copy');b.type='button';b.setAttribute('aria-label','Copy '+did);b.onclick=async()=>{try{await navigator.clipboard.writeText(did);$('toast').textContent='DID copied';}catch{$('toast').textContent='Copy unavailable. Select the DID in its details.';}setTimeout(()=>$('toast').textContent='',3500);};return b;}
function didCell(did){const td=el('td'),row=el('div',undefined,'did-row'),d=el('details');const summary=el('summary',did.slice(0,16)+'…'+did.slice(-8),'did');d.append(summary,el('p',did));row.append(d,copyButton(did));td.append(row);return td;}
function card(label,value,meta,kind='published'){const c=el('article',undefined,'card');c.append(el('label',label),el('strong',fmt(value)),el('small',`${kind.toUpperCase()} · ${meta}`));return c;}
function countdown(time){let s=Math.floor((Date.parse(time)-Date.now())/1000);if(s<=0)return 'Scheduled time passed';return `${Math.floor(s/86400)}d ${Math.floor(s%86400/3600)}h ${Math.floor(s%3600/60)}m`;}
function current(t){return feeds[t]?.data||{};}
function meta(t){const f=feeds[t];return f?.data?`Sweep ${f.data.n} · ${stamp(f.envelope.ts)} · ${feedStatus(f)}`:'No usable record';}
function renderCards(){const p=current('price'),l=current('pnl');const ns=ROOMS.map(t=>current(t).n).filter(Number.isInteger);const same=ns.length===5&&new Set(ns).size===1;
$('cards').replaceChildren(card('Sweep',same?ns[0]:ns.length?'Mixed':'—',same?'5 referee rooms aligned':'See data health'),card('Live mark',l.mark?`${l.mark} POLF`:'—','Referee scoring mark'),card('NVDA reference',p.ref?.px?`${p.ref.px} POLF`:'—',p.ref?.time?stamp(p.ref.time):'Price room'),card('Trading closes',countdown('2026-10-04T09:00:00Z'),'4 Oct · 09:00 UTC','derived'));
}
function renderPnl(){const p=current('pnl'),f=feeds.pnl,body=$('pnl-body');body.replaceChildren();$('pnl-meta').textContent=`Sweep ${fmt(p.n)} · mark ${fmt(p.mark)} POLF · ${p.top?.length??0} published`;
if(!p.top?.length){const td=el('td',f?.data?'Published Top list is empty. No account status can be inferred.':'No usable PnL feed. Check data health.');td.colSpan=3;const tr=el('tr');tr.append(td);body.append(tr);return;}
for(const g of groups(p.top))for(const [i,[did,score]] of g.rows.entries()){const tr=el('tr');const span=g.boundary?`${g.start}–?`:g.start===g.end?`${g.start}`:`${g.start}–${g.end}`;
const tie=g.boundary?`At least ${g.count} visible at this score; the tie may continue beyond Top 25.`:g.count>1?`${g.count} equal published scores`:'';
const place=el('td');place.append(el('strong',span,'place'));if(i===0&&tie)place.append(el('small',tie,'tie'));
tr.append(place,didCell(did),el('td',score));body.append(tr);}
}
function renderPositions(){const p=current('positions'),body=$('positions-body');body.replaceChildren();$('positions-meta').textContent=`${meta('positions')} · ${p.top?.length??0} listed positions`;
const sum=typeof p.longs==='number'&&typeof p.shorts==='number'?p.longs+p.shorts:0;const imbalance=sum?`${((p.longs-p.shorts)/sum*100).toFixed(2)}%`:'Not derivable';
$('market').replaceChildren(card('Long owners',p.longs,meta('positions')),card('Short owners',p.shorts,meta('positions')),card('Owner-count imbalance',imbalance,'(long owners − short owners) / total · not volume','derived'));
const pnl=compatible(feeds.positions,feeds.pnl)?new Map(current('pnl').top):new Map();
for(const [did,position] of p.top||[]){const n=decimal(position),side=n==='0'?'ZERO (published)':n.startsWith('-')?'SHORT':'LONG';const tr=el('tr');tr.append(didCell(did),el('td',position),el('td',side),el('td',position.replace(/^-/,'')),el('td',pnl.get(did)??'Not published'),el('td',p.n));body.append(tr);}
if(!p.top?.length){const tr=el('tr'),td=el('td','No published positions loaded.');td.colSpan=6;tr.append(td);body.append(tr);}
}
function renderFlow(){const f=current('flow');$('flow-meta').textContent=meta('flow');$('flow-counts').replaceChildren();for(const key of ['mints','settled','void']){$('flow-counts').append(card(`Visible ${key}`,Array.isArray(f[key])?f[key].length:undefined,'Count of listed entries','derived'),card(`Omitted ${key}`,f.omitted?.[key],f.omitted?.[key]===undefined?'Field not published; not assumed zero':'Count explicitly published'));}
const counts=new Map();for(const v of f.void||[]){if(Array.isArray(v)&&typeof v[1]==='string')counts.set(v[1],(counts.get(v[1])||0)+1);else counts.set('Unrecognised reason shape',(counts.get('Unrecognised reason shape')||0)+1);}
$('voids').textContent=counts.size?[...counts].map(([k,v])=>`${k}: ${v}`).join(' · '):'No visible reasons loaded';$('missed').textContent=f.missed?JSON.stringify(f.missed,null,2):'Not published';$('raw-flow').textContent=JSON.stringify(feeds.flow?.envelope||{},null,2);
}
function renderHealth(){const rows=$('health');rows.replaceChildren();let warnings=[];for(const t of ROOMS){const f=feeds[t],status=feedStatus(f);const row=el('article',undefined,'feed'),a=el('a',`d-close1-${t}`);a.href=endpoint(t);const detail=el('div');detail.append(el('p',meta(t)),el('p',`Last successful read: ${f?.fetchedAt?stamp(f.fetchedAt):'None'} · ${f?.signature??'Signature not checked'}`),el('p',`File hash: ${f?.data?.file??'Not published'}`));if(f?.data?.root)detail.append(el('p',`State root: ${f.data.root}`));if(f?.error)detail.append(el('p',f.error,'ERROR'));if(f?.errors?.length)detail.append(el('p',`${f.errors.length} malformed/untrusted record(s) skipped: ${[...new Set(f.errors)].join('; ')}`,'PARTIAL'));row.append(a,el('span',status,`badge ${status}`),detail);rows.append(row);if(status!=='LIVE')warnings.push(`${t}: ${status}`);}
const present=ROOMS.filter(t=>feeds[t]?.data),mismatch=present.length>1&&present.some(t=>!compatible(feeds[t],feeds[present[0]]));const omitted=Object.values(current('flow').omitted||{}).some(x=>Number(x)>0);const noSig=present.some(t=>feeds[t].signature!=='Envelope signature checked');
const status=present.length===0?'ERROR':present.some(t=>feedStatus(feeds[t])==='STALE')?'STALE':warnings.length||mismatch||omitted||noSig?'PARTIAL':'LIVE';$('overall').textContent=status==='PARTIAL' && present.length===5 && !warnings.length && !mismatch ? 'LIVE · PARTIAL DATA' : status;$('overall').className=`badge ${status}`;
$('sync').textContent=(mismatch?'SYNC WARNING — Room sweeps or file hashes differ. Cross-room DID joins are disabled. ':present.length<5?'Some referee rooms have no usable data. ':'Room sweep and file hashes agree. ')+(omitted?'Flow explicitly omits events. ':'')+(warnings.length?warnings.join(' · ')+'. ':'')+'Top lists never represent every owner.';
$('last').textContent=lastSuccess?`All five last read: ${stamp(lastSuccess)}`:'No complete five-room refresh yet';}
function renderSearch(){const q=$('search').value.trim(),out=$('search-results');out.replaceChildren();if(!q)return;const matches=search(index,q);if(!matches.length){out.append(el('p',UNKNOWN));if(!Object.keys(feeds).length||ROOMS.some(t=>!feeds[t]?.data||feeds[t].error))out.append(el('p','Coverage is incomplete because one or more feeds could not be loaded.'));return;}
out.append(el('p',`${matches.length} observed DID match${matches.length===1?'':'es'} · case-sensitive · session history only`));for(const [did,sightings] of matches.slice(0,100)){const r=el('div',undefined,'result');r.append(el('strong',did),copyButton(did));for(const type of [...new Set(sightings.map(s=>s.type))]){const all=sightings.filter(s=>s.type===type).sort((a,b)=>a.n-b.n),first=all[0],latest=all.at(-1),label=type==='pnl'?'PnL Top 25':type==='positions'?'Largest positions':'Recent flow';const range=first.n===latest.n?`sweep ${latest.n}`:`sweeps ${first.n}–${latest.n}`;r.append(el('p',`${label} · ${all.length} observation${all.length===1?'':'s'} · ${range} · latest ${stamp(latest.ts)}`));}out.append(r);}if(matches.length>100)out.append(el('p','Showing the first 100 matches. Refine the DID.'));}
function render(){renderCards();renderPnl();renderPositions();renderFlow();renderHealth();index=observations(history);renderSearch();}
async function refresh(){if(busy||Date.now()-lastAttempt<60000)return;busy=true;lastAttempt=Date.now();$('refresh').disabled=true;await Promise.all(ROOMS.map(async type=>{try{const response=await fetch(endpoint(type),{credentials:'omit',signal:AbortSignal.timeout(20000)});if(!response.ok)throw Error(`HTTP ${response.status}`);const decoded=decodeRoom(await response.json(),type),verified=[];let signature='Envelope signature checked';for(const item of decoded.records){try{if(!await verifyEnvelope(item.envelope,`d-close1-${type}`)){decoded.errors.push('Invalid signature rejected');continue;}}catch(e){if(e.name==='NotSupportedError'||!globalThis.crypto?.subtle){signature='Signature verification unavailable';}else{decoded.errors.push(`Signature check failed: ${e.message}`);continue;}}verified.push(item);}if(!verified.length)throw Error('No valid referee records after signature checks');const latest=verified.at(-1),old=feeds[type];if(old?.data&&(latest.data.n<old.data.n||latest.envelope.seq<old.envelope.seq))throw Error('Feed regressed; previous record retained');feeds[type]={...latest,signature,errors:decoded.errors,fetchedAt:new Date().toISOString()};const merged=new Map(history[type].map(x=>[x.envelope.seq,x]));for(const item of verified)merged.set(item.envelope.seq,item);history[type]=[...merged.values()].sort((a,b)=>a.envelope.seq-b.envelope.seq).slice(-200);}catch(e){feeds[type]={...feeds[type],error:`Read failed: ${e.message}. Network/CORS failures cannot be distinguished here. Retained data is labelled by age.`};}}));busy=false;if(ROOMS.every(t=>feeds[t]?.data&&!feeds[t].error))lastSuccess=new Date().toISOString();render();}
$('refresh').onclick=refresh;$('search').oninput=renderSearch;document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-panel]').forEach(n=>{n.classList.toggle('selected',n===b);n.setAttribute('aria-pressed',String(n===b));});document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==`panel-${b.dataset.panel}`);});
for(const t of ROOMS){const li=el('li'),a=el('a',`Referee room d-close1-${t}`);a.href=`https://technocore.chat/r/d-close1-${t}`;li.append(a);$('links').append(li);}
setInterval(()=>{const left=Math.max(0,Math.ceil((60000-(Date.now()-lastAttempt))/1000));$('refresh').disabled=busy||left>0;$('refresh').textContent=busy?'Reading…':left?`Refresh in ${left}s`:'Refresh feeds';renderCards();renderHealth();if(!document.hidden&&!busy&&!left)refresh();},1000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});render();refresh();
